### ISSUE TITLE
Characters " []()" seem don't need to be escaped

### ISSUE THREAD

**Issue by Onway** [ArxOne/FTP#15]
Without escaping, ParenthesisNameTest, BracketsNameTest and SpaceNameTest also work well. 
And that if escaping, these tests will fail by Fillzilla on Windows and vsftpd in LIST command, 
and when exception throw, the test code will be blocking by filezilla but vsftpd won't.

Besides, above three tests also fail since Fillzilla Server on Windows unsupported STAT command.

**Comment by picrap** [comment]
The tests fail on pure-ftpd without escaping, and it's the ftp server I'm using :smile: 
Regarding FileZilla and `STAT` support, I am sorry about that, but there too, I'm using pure-ftpd and it supports this command.
In a more pragmatic way, what are your suggestions? Changing tests? Let me know if you have ideas, since they're always welcome.

**Comment by Onway** [comment]
I test with pure-ftpd v1.0.36 on CentOS 7, here is the result: 
![image](https://cloud.githubusercontent.com/assets/3352864/8723568/5acf8ed8-2c01-11e5-8926-509548559bef.png)
It seems only the "space" character is controversial. 
But in any case, in my opinion, escape or not should be determined by user. 
What do you think about this problem?

**Comment by picrap** [comment]
Currently I added a `FtpPlatform` which can be provided as a parameter to the `FtpClient` (via `FtpParameters`). You can provide your own implementation, in order to avoid any escaping.
Regarding the brackets and parenthesis, that's right, I made a blind fix for someone who had the problem (and the fix workd). Since it also works with other ftp servers, I keep the escaping, even if it is not always necessary.
So, I you don't have an objection, I'm going to close this issue.
Is it OK for you?

**Comment by Onway** [comment]
Yes, I have saw the constructor of `FtpClient`, it's OK to close this issue.

**Comment by picrap** [comment]
:+1:
